Using `numpy`
----

### Importing libraries and configuration

In [ ]:
%matplotlib inline
from __future__ import division
import matplotlib.pyplot as plt
import numpy as np

### Inedexing with lists

In [1]:
xs = range(10)
xs

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
xs[0]

0

In [3]:
xs[-1]

9

In [6]:
xs[2:7]

[2, 3, 4, 5, 6]

In [7]:
xs[2:7:2]

[2, 4, 6]

In [8]:
xs[5:]

[5, 6, 7, 8, 9]

In [9]:
xs[:5]

[0, 1, 2, 3, 4]

### Using `numpy` arrays

In [11]:
np.array([1,2,3])

array([1, 2, 3])

In [13]:
np.array([[1,2,3],
          [4,5,6],
          [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [16]:
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [17]:
np.arange(0, 1, 0.1)

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9])

### Indexing `numpy` arrays

In [2]:
v = np.arange(1, 19, 2)
v

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [3]:
v[2:5]

array([5, 7, 9])

In [4]:
v[-2:]

array([15, 17])

In [5]:
v[::3]

array([ 1,  7, 13])

In [6]:
v[1::2]

array([ 3,  7, 11, 15])

#### Sorting and reversing

In [8]:
v.sort()
v

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17])

In [56]:
v[::-1]

array([17, 15, 13, 11,  9,  7,  5,  3,  1])

#### Working with 2D arrays

In [15]:
w = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [105]:
w[1]

array([4, 5, 6, 7])

In [59]:
w[1,:]

array([4, 5, 6, 7])

In [60]:
w[:,0]

array([0, 4, 8])

In [61]:
w[:, 1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [62]:
w[::2, 2:3]

array([[ 2],
       [10]])

#### Sorting a 2D array

In [46]:
np.random.seed(123)
ns = np.random.randint(0, 10, 24).reshape((6,4))
ns

array([[2, 2, 6, 1],
       [3, 9, 6, 1],
       [0, 1, 9, 0],
       [0, 9, 3, 4],
       [0, 0, 4, 1],
       [7, 3, 2, 4]])

#### Sort by 1st column then by 3rd column

In [76]:
np.sort(ns.view('i8,i8,i8,i8'), order=['f0', 'f2'], axis=0).view(np.int)

array([[0, 9, 3, 4],
       [0, 0, 4, 1],
       [0, 1, 9, 0],
       [2, 2, 6, 1],
       [3, 9, 6, 1],
       [7, 3, 2, 4]])

#### Much nicer in `pandas`

In [68]:
np.random.seed(123)
ns = np.random.randint(0, 10, 24).reshape((6,4))
ns

array([[2, 2, 6, 1],
       [3, 9, 6, 1],
       [0, 1, 9, 0],
       [0, 9, 3, 4],
       [0, 0, 4, 1],
       [7, 3, 2, 4]])

In [85]:
from pandas import DataFrame

df = DataFrame(ns)
df = df.sort(columns=[0,2])
df.values

array([[0, 9, 3, 4],
       [0, 0, 4, 1],
       [0, 1, 9, 0],
       [2, 2, 6, 1],
       [3, 9, 6, 1],
       [7, 3, 2, 4]])

### Fancy indexing

In [64]:
v[[2, 4, 7]]

array([ 5,  9, 15])

In [67]:
w[[0,2],[1,3]]

array([ 1, 11])

### Logical indexing

In [72]:
v > 5

array([False, False, False,  True,  True,  True,  True,  True,  True], dtype=bool)

In [68]:
v[v > 5]

array([ 7,  9, 11, 13, 15, 17])

In [69]:
v[v <= 5]

array([1, 3, 5])

In [71]:
w[w % 2 == 1]

array([ 1,  3,  5,  7,  9, 11])

### Resizing arrays

In [106]:
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [109]:
w.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [118]:
w.reshape((12,))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [119]:
w.reshape((1,12))

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [115]:
w.reshape((12,1))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [121]:
w.reshape((6,2))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [125]:
w.reshape((-1,6))

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [128]:
w.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

### Element-wise operations

In [19]:
x = np.array([1,2,3])
y = x + 3
y

array([4, 5, 6])

In [20]:
x * y

array([ 4, 10, 18])

In [24]:
y**2

array([16, 25, 36])

### Universaf functions

In [21]:
len(x)

3

In [22]:
x.shape

(3,)

In [30]:
xs = np.arange(1, 13).reshape((3,4))
xs

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
xs.shape

(3, 4)

In [31]:
np.log2(xs)

array([[ 0.        ,  1.        ,  1.5849625 ,  2.        ],
       [ 2.32192809,  2.5849625 ,  2.80735492,  3.        ],
       [ 3.169925  ,  3.32192809,  3.45943162,  3.5849625 ]])

### Summarising data

In [75]:
w.sum()

66

In [76]:
np.sum(w)

66

In [77]:
w.mean()

5.5

In [78]:
np.var(w)

11.916666666666666

In [79]:
w.max()

11

#### Summaring across rows

In [80]:
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
w.sum(axis=0)

array([12, 15, 18, 21])

#### Summarizing across colums

In [82]:
w.sum(axis=1)

array([ 6, 22, 38])

### Combining arrays

In [97]:
w

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
np.hstack([w,w])

array([[ 0,  1,  2,  3,  0,  1,  2,  3],
       [ 4,  5,  6,  7,  4,  5,  6,  7],
       [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [99]:
np.vstack([w,w])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [101]:
np.hstack([w, w[:, 3:]])

array([[ 0,  1,  2,  3,  3],
       [ 4,  5,  6,  7,  7],
       [ 8,  9, 10, 11, 11]])

In [102]:
np.vstack([w, w[1:3,:]])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Exercises
----

Use the vector `xs` given below to answer the follwoing questions.

In [133]:
xs = np.arange(1, 25)
xs

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

**1.** Extract the elements with indices 7 to 10 (inclusive).

**2.** Convert to a 4 by 6 matrix and save as the variable `ys`.

**3.** Find the row and column averages for `ys`.

**4.** Extract the middle 2 by 4 submatrix from `ys` - i.e. excluding the first and last rows and columns.

**5.** Append two rows consisting of all ones to `ys`.